.\" Manpage for eacct.
.TH man 1 "28 October 2020" "3.3" "eacct man page"
.SH NAME
eacct \- See a report of the last job executions reported by EAR's daemons.
.SH SYNOPSIS
eacct [options]

.SH DESCRIPTION

eacct is a simple command to see a jobs' energy accounting information. It can also retrieve EARL events that occurred on a job execution.

.SH OPTIONS

    -h      displays this message
    -v      displays current EAR version
    -b      verbose mode for debugging purposes
    -u      specifies the user whose applications will be retrieved. Only available to privileged users. [default: all users]
    -j      specifies the job id and step id to retrieve with the format [jobid.stepid] or the format [jobid1,jobid2,...,jobid_n].
                A user can only retrieve its own jobs unless said user is privileged. [default: all jobs]
    -c      specifies the file where the output will be stored in CSV format. [default: no file]
    -t      specifies the energy_tag of the jobs that will be retrieved. [default: all tags].
    -l      shows the information for each node for each job instead of the global statistics for said job.
    -x      shows the last EAR events. Nodes, job ids, and step ids can be specified as if were showing job information.
    -r      shows the EAR loop signatures. Nodes, job ids, and step ids can be specified as if were showing job information.
    -n      specifies the number of jobs to be shown, starting from the most recent one. [default: 20][to get all jobs use -n all]
    -f      specifies the file where the user-database can be found. If this option is used, the information will be read from the file and not the database.
    
.SH Usage examples

Job 31191 corresponds with the execution of the bqcd application with 5 job steps. When executing eacct -j 31191 we will get the following output:

[user@host EAR]$ eacct -j 31191
    JOBID     USER    APP      POLICY NODES FREQ(GHz) TIME(s)   POWER(Watts)  GBS        CPI        ENERGY (J)     
    31191.4   user  bqcd_cpu   ME     50    2.27      398.38    229.09        4.26       1.00       4563306.92    
    31191.3   user  bqcd_cpu   ME     50    2.28      394.89    230.84        4.30       0.98       4557703.38    
    31191.2   user  bqcd_cpu   MO     50    2.38      316.31    272.27        5.35       0.92       4306123.40    
    31191.1   user  bqcd_cpu   MO     50    2.38      319.97    271.79        5.29       0.92       4348172.40    
    31191.0   user  bqcd_cpu   MO     50    2.38      317.04    269.67        5.34       0.91       4274739.44   
 

The following instead retrieves the first EARL events for the previous job:

[user@host EAR]$ eacct -j 31191 -x -n 15
    Event ID            Timestamp      Event type   Job id  Step id                Freq.      node_id
    21205     2018-09-19 09:24:24      DYNAIS OFF    31191        5                    0      cmp2615 
    21206     2018-09-19 09:24:24      DYNAIS OFF    31191        5                    0      cmp2614 
    21204     2018-09-19 09:23:43        NEW FREQ    31191        5              2200000      cmp2742 
    21192     2018-09-19 09:23:17        NEW FREQ    31191        5              2300000      cmp2605 
    21193     2018-09-19 09:23:17        NEW FREQ    31191        5              2200000      cmp2769 
    21194     2018-09-19 09:23:17        NEW FREQ    31191        5              2200000      cmp2763 
    21195     2018-09-19 09:23:17        NEW FREQ    31191        5              2200000      cmp2749 
    21196     2018-09-19 09:23:17        NEW FREQ    31191        5              2300000      cmp2620 
    21197     2018-09-19 09:23:17        NEW FREQ    31191        5              2200000      cmp2632 
    21198     2018-09-19 09:23:17        NEW FREQ    31191        5              2200000      cmp2745 
    21199     2018-09-19 09:23:17        NEW FREQ    31191        5              2200000      cmp2733 
    21200     2018-09-19 09:23:17        NEW FREQ    31191        5              2200000      cmp2604 
    21201     2018-09-19 09:23:17        NEW FREQ    31191        5              2200000      cmp2610 
    21202     2018-09-19 09:23:17        NEW FREQ    31191        5              2300000      cmp2742 
    21203     2018-09-19 09:23:17        NEW FREQ    31191        5              2200000      cmp2611 
 



.SH BUGS
    - Saving the output to a file with the -c option and then reading it with -f may cause some issues if there are empty fields.
.SH SEE ALSO
ereport(1), econtrol(1), EAR(8)
.SH AUTHOR
EAR support team (ear-support@bsc.es)
