RLPATH = $(subst $(SRCDIR),.,$(shell pwd))
RLPATH = $(shell realpath $(SRCDIR) --relative-to=$(shell pwd))

######## RULES

depend: rdepend

rdepend: $(wildcard ./*.c)
	@ rm -f ./.depend
	@ $(CC) -I $(RLPATH) -MM -MG $^ >> ./.depend;

depend-clean:
	@ rm -f .depend

-include .depend
