.\" Manpage for ear_create_database.
.TH man 8 "August 2024" "5.0" "ear-info man page"
.SH NAME
ear-info \- General EAR configuration information.
.SH SYNOPSIS
ear-info
.SH DESCRIPTION
ear-info displays current compile-time definitions for EAR, as well as current EAR-specific environment variables set.

Additionally, one can request to do a status check on a certain node to see the current services available there (EARD/EARGM/EARDBD).

.SH OPTIONS
 --node-conf=nodename    requests the status of the EAR services in nodename

.SH BUGS
No known bugs.
.SH AUTHOR
EAR suport team (ear-support@bsc.es)
